name: Site Build and Deploy

on:
  push:
    branches: [ master ]
    tags:
      - '!refs/tags/*'
    paths-ignore:
      - '**/README.md'
      - '**/.github/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**/.github/**'

jobs:
  build-project:
    name: 'Build and Deploy'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '8' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          check-latest: true
          cache: maven

      - name: Build Project Site
        run: mvn site site:stage

      - name: Deploy Site
        if: github.ref == 'refs/heads/master' && matrix.java == 8
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/staging