name: Site Builds

on:
  release:
    types: [ published ]
  workflow_dispatch:


jobs:
  build-project:
    name: 'Build and Deploy'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '8' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          check-latest: true
          cache: maven

      - name: Build Project Site
        run: mvn site site:stage -Dchangelist=

      - name: Deploy Site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/staging